repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
    stages: [commit]
  - id: end-of-file-fixer
    stages: [commit]
  - id: check-yaml
    stages: [commit]
  - id: check-added-large-files
    stages: [commit]
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.3.5
  hooks:
  - id: reorder-python-imports
    stages: [commit]
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v1.11.0
  hooks:
  - id: setup-cfg-fmt
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.782
  hooks:
  - id: mypy
    args: [--no-strict-optional, --ignore-missing-imports]
- repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint
    stages: [commit]
- repo: https://github.com/codespell-project/codespell
  rev: v1.17.1
  hooks:
  - id: codespell
    exclude: ^eel_ui/frontend/yarn.lock$
    stages: [commit]
- repo: https://gitlab.com/smop/pre-commit-hooks
  rev: v1.0.0
  hooks:
  - id: check-poetry
    stages: [commit]
- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
  - id: black
